# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Russian spellchecker"
ru = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Russian, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
ru = "TRANSLATE: A spellchecker for Russian, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.ru"

[windows]
system_product_code = "{DEC7DA72-842B-4385-916E-0AEDA6329553}_is1"
legacy_product_codes = [
    { value = "8269141F-4C59-4038-97BC-24736F91131D", kind = "nsis" },
    { value = "DB5D1126-5BC7-4B3E-9ABB-2AA097239B0B", kind = "nsis" }
]

[package.speller]
name = "Russian"
version = "0.1.1"

[package.grammar]
name = "Russian"
version = "0.1.0"

[package.tts-text-proc]
name = "Russian"
version = "0.1.0"
