template = "https://github.com/giellalt/template-lang-und"
rev_id = 264
template_sha = "120f384c016282eb1fbbcc762e0ac6064a37eb45"

[replacements]
__GLOTTOLOG_ID__ = "russ1263"
__REPO__ = "lang-rus"
__UND2C__ = "ru"
__UNDEFINED__ = "Russian"
__UND__ = "rus"
