template = "https://github.com/giellalt/template-lang-und"
rev_id = 271
template_sha = "58889500fa56906fc67098b753f74968988220af"

[replacements]
__GLOTTOLOG_ID__ = "russ1263"
__REPO__ = "lang-rus"
__UND2C__ = "ru"
__UNDEFINED__ = "Russian"
__UND__ = "rus"
